# Generated by Django 4.2.13 on 2024-06-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('searcher', '0002_alter_education_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='desired_positions',
            field=models.ManyToManyField(related_name='resumes', to='company.jobposition'),
        ),
    ]
