# Generated by Django 4.2.13 on 2024-06-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('searcher', '0003_alter_resume_desired_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='desired_positions',
            field=models.ManyToManyField(blank=True, related_name='resumes', to='company.jobposition'),
        ),
    ]
