# Generated by Django 4.2.13 on 2024-05-31 22:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='articles/', verbose_name='Картинка')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('author_position', models.CharField(max_length=255, verbose_name='Посада автора')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Перегляди')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='CommentArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('number_of_employees', models.IntegerField(choices=[(10, 'До 10 працівників '), (50, 'Від 10 до 50 працівників'), (100, 'Від 50 до 100 працівників'), (250, 'Від 100 до 250 працівників'), (500, 'Більше 500 працівників')], verbose_name='Кількість працівників')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('has_link', models.BooleanField(default=False, verbose_name='Посилання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Хештег')),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Назва на російській мові')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг')),
                ('categories', models.ManyToManyField(related_name='job_positions_by_category', to='company.jobcategory', verbose_name='Категорії')),
            ],
        ),
        migrations.CreateModel(
            name='JobPositionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_comment', models.CharField(blank=True, max_length=30, null=True, verbose_name='Коментар до посади')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефону')),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата мін')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата макс')),
                ('employment_type', models.CharField(blank=True, choices=[('full', 'Повна зайнятісь'), ('part', 'Неповна зайнятісь'), ('shift', 'Позмінна робота')], max_length=10, null=True, verbose_name='Тип зайнятості')),
                ('work_type', models.CharField(blank=True, choices=[('internship', 'Стажування/практика'), ('remote', 'Відалена робота'), ('office', 'Робота в офісі'), ('hybrid', 'Гібридна робота')], max_length=15, null=True, verbose_name='Харакатер роботи')),
                ('description', models.TextField(verbose_name='Опис')),
                ('social_networks', models.BooleanField(default=False, verbose_name='Соц.Мережі')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час публікації')),
                ('status', models.CharField(choices=[('standard', 'Стандарт'), ('standard_plus', 'Стандарт плюс'), ('hot', 'Гаряча'), ('hidden', 'Прихована')], max_length=15, verbose_name='Статус')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Компанія')),
                ('hashtags', models.ManyToManyField(blank=True, to='company.hashtag', verbose_name='Хештеги')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='company.jobposition', verbose_name='Посада')),
            ],
        ),
        migrations.AddField(
            model_name='jobposition',
            name='groups',
            field=models.ManyToManyField(related_name='job_positions_by_group', to='company.jobpositiongroup', verbose_name='Групи'),
        ),
    ]
