# Generated by Django 4.2.13 on 2024-07-27 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='articles/', verbose_name='Картинка')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('author_position', models.CharField(max_length=255, verbose_name='Посада автора')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Перегляди')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='CommentArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('number_of_employees', models.IntegerField(choices=[(10, 'До 10 працівників '), (50, 'Від 10 до 50 працівників'), (100, 'Від 50 до 100 працівників'), (250, 'Від 100 до 250 працівників'), (500, 'Більше 500 працівників')], verbose_name='Кількість працівників')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('has_link', models.BooleanField(default=False, verbose_name='Посилання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Хештег')),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Назва на російській мові')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='JobPositionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_comment', models.CharField(blank=True, max_length=30, null=True, verbose_name='Коментар до посади')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефону')),
                ('min_salary', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Зарплата мін')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Зарплата макс')),
                ('employment_type', models.CharField(blank=True, choices=[('full', 'Повна зайнятісь'), ('part', 'Неповна зайнятісь'), ('shift', 'Позмінна робота')], max_length=10, null=True, verbose_name='Тип зайнятості')),
                ('education_level', models.CharField(choices=[('high_school', 'Середня'), ('vocational_school', 'Середня спеціальна'), ('incomplete_higher', 'Незакінчена вища'), ('higher_education', 'Вища')], max_length=20)),
                ('description', models.TextField(verbose_name='Опис')),
                ('social_networks', models.BooleanField(default=False, verbose_name='Соц.Мережі')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час публікації')),
                ('status', models.CharField(choices=[('standard', 'Стандарт'), ('standard_plus', 'Стандарт плюс'), ('hot', 'Гаряча'), ('hidden', 'Прихована')], max_length=15, verbose_name='Статус')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Кількість переглядів')),
                ('experience', models.CharField(choices=[('no_experience', 'Можна без досвіду'), ('preferred_experience', 'Досвід буде перевагою'), ('one_year', 'Досвід від 1-го року'), ('two_years', 'Досвід від 2-х років'), ('more_than_five_years', 'Досвід більше 5 років')], default='no_experience', max_length=20, verbose_name='Досвід роботи')),
                ('schedule', models.CharField(choices=[('standard_5_2', 'Стандартний графік 5/2'), ('shift_4_4', 'Позмінний графік 4/4'), ('shift_2_2_4', 'Позмінний графік 2/2/4'), ('shift_4_2', 'Позмінний графік 4/2'), ('duty_1_3', 'Чергування доба/3 вихідних'), ('floating', 'Плаваючий графік'), ('free', 'Вільний графік'), ('part_time', 'Підробіток (не повний день)')], default='standard_5_2', max_length=20, verbose_name='Графік роботи')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Початківець'), ('basic', 'Базовий рівень'), ('intermediate', 'Впевнений користувач'), ('advanced', 'Вільно'), ('native', 'Рідна')], max_length=20)),
            ],
            options={
                'verbose_name': 'Vacancy Language',
                'verbose_name_plural': 'Vacancy Languages',
            },
        ),
    ]
