# Generated by Django 4.2.13 on 2024-07-27 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancylanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_languages', to='resume.language'),
        ),
        migrations.AddField(
            model_name='vacancylanguage',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_languages', to='company.vacancy'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Компанія'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='company.hashtag', verbose_name='Хештеги'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='company.jobposition', verbose_name='Посада'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='categories',
            field=models.ManyToManyField(related_name='job_positions_by_category', to='company.jobcategory', verbose_name='Категорії'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='groups',
            field=models.ManyToManyField(related_name='job_positions_by_group', to='company.jobpositiongroup', verbose_name='Групи'),
        ),
        migrations.AddField(
            model_name='company',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'role': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='administered_companies', to=settings.AUTH_USER_MODEL, verbose_name='Адміністратор'),
        ),
        migrations.AddField(
            model_name='commentarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='company.article'),
        ),
        migrations.AddField(
            model_name='commentarticle',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='company.commentarticle'),
        ),
        migrations.AddField(
            model_name='commentarticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AddField(
            model_name='articlesection',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='company.article', verbose_name='Стаття'),
        ),
    ]
